# Generated by Django 3.2.16 on 2023-01-27 12:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('prompt', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectPrompts',
            fields=[
                ('projectPromptId', models.BigAutoField(primary_key=True, serialize=False)),
                ('promptFields', models.CharField(blank=True, max_length=65535, null=True)),
                ('createdBy', models.IntegerField()),
                ('createdOnUtc', models.DateTimeField(auto_now_add=True)),
                ('modifiedBy', models.IntegerField()),
                ('modifiedOnUtc', models.DateTimeField(auto_now=True)),
                ('isDeleted', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('projectId', models.BigAutoField(primary_key=True, serialize=False)),
                ('userId', models.IntegerField(default=0)),
                ('name', models.CharField(max_length=200)),
                ('description', models.CharField(blank=True, max_length=2000, null=True)),
                ('createdBy', models.IntegerField()),
                ('createdOnUtc', models.DateTimeField(auto_now_add=True)),
                ('modifiedBy', models.IntegerField()),
                ('modifiedOnUtc', models.DateTimeField(auto_now=True)),
                ('isDeleted', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='PromptResponses',
            fields=[
                ('responseId', models.BigAutoField(primary_key=True, serialize=False)),
                ('response', models.CharField(blank=True, max_length=65535, null=True)),
                ('language', models.CharField(blank=True, max_length=200, null=True)),
                ('createdBy', models.IntegerField()),
                ('createdOnUtc', models.DateTimeField(auto_now_add=True)),
                ('modifiedBy', models.IntegerField()),
                ('modifiedOnUtc', models.DateTimeField(auto_now=True)),
                ('isDeleted', models.BooleanField(default=False)),
                ('promptId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.projectprompts')),
            ],
        ),
        migrations.AddField(
            model_name='projectprompts',
            name='projectId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.projects'),
        ),
        migrations.AddField(
            model_name='projectprompts',
            name='promptId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='prompt.prompt'),
        ),
    ]
