# Generated by Django 3.2.16 on 2023-02-06 07:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0001_initial'),
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projects',
            name='userId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pricing.user'),
        ),
    ]
