# Generated by Django 3.2.16 on 2023-02-28 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_alter_projects_userid'),
    ]

    operations = [
        migrations.AddField(
            model_name='promptresponses',
            name='responseType',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
