# Generated by Django 3.2.16 on 2023-01-27 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Prompt',
            fields=[
                ('promptId', models.BigAutoField(primary_key=True, serialize=False)),
                ('promptName', models.CharField(max_length=200)),
                ('promptText', models.CharField(blank=True, max_length=2000, null=True)),
                ('description', models.CharField(blank=True, max_length=2000, null=True)),
                ('createdBy', models.IntegerField()),
                ('createdOnUtc', models.DateTimeField(auto_now_add=True)),
                ('modifiedBy', models.IntegerField()),
                ('modifiedOnUtc', models.DateTimeField(auto_now=True)),
                ('isDeleted', models.BooleanField(default=False)),
            ],
        ),
    ]
