# Generated by Django 3.2.16 on 2023-02-07 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prompt', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='prompt',
            name='promptSubCategory',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
