# Generated by Django 3.2.16 on 2023-02-13 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prompt', '0003_auto_20230213_1355'),
    ]

    operations = [
        migrations.AddField(
            model_name='prompt',
            name='promptPostUrl',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
