# Generated by Django 3.2.16 on 2023-02-14 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prompt', '0004_prompt_promptposturl'),
    ]

    operations = [
        migrations.RenameField(
            model_name='prompt',
            old_name='image',
            new_name='backImage',
        ),
        migrations.AddField(
            model_name='prompt',
            name='frontImage',
            field=models.FileField(default='static/images/logo.png', upload_to='static/images/prompts'),
        ),
        migrations.AddField(
            model_name='prompt',
            name='promptGetUrl',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
